services:
  - type: web
    name: rabotec-tool-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: rabotec-postgres
    databaseName: rabotec_tools
    user: rabotec_user
    plan: free
